package com.leetcode.fourhundred;

/**
 * https://leetcode.com/problems/find-the-difference/
 * <p>
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 * <p>
 * Example:
 * <p>
 * Input:
 * s = "abcd"
 * t = "abcde"
 * <p>
 * Output:
 * e
 * <p>
 * Explanation:
 * 'e' is the letter that was added.
 *
 * @author carl
 */
public class FindtheDifference {

    public char findTheDifference(String s, String t) {
        int[] counter = new int[256];
        for (char c : s.toCharArray()) {
            counter[c]++;
        }
        for (char c : t.toCharArray()) {
            if (--counter[c] < 0) {
                return c;
            }
        }
        return '0';
    }
}
